
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 01 22:45:31 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LPARENT = 13;
  public static final int RPARENT = 14;
  public static final int DIVEQ = 46;
  public static final int PLUSPLUS = 23;
  public static final int LBRACKET = 9;
  public static final int CONST = 7;
  public static final int MODEQ = 45;
  public static final int NUMCONST = 47;
  public static final int SEMI = 8;
  public static final int CONTINUE = 19;
  public static final int FOR = 17;
  public static final int MINUS = 26;
  public static final int GRE = 31;
  public static final int AND = 27;
  public static final int OR = 28;
  public static final int COMMA = 6;
  public static final int CLASS = 15;
  public static final int DIV = 40;
  public static final int PLUSEQ = 42;
  public static final int MINUSEQ = 43;
  public static final int PLUS = 35;
  public static final int SMLEQUAL = 34;
  public static final int IF = 16;
  public static final int DOT = 37;
  public static final int SML = 33;
  public static final int ABSTRACT = 11;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 24;
  public static final int RETURN = 21;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 5;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int ISEQUAL = 29;
  public static final int MUL = 39;
  public static final int IDENT = 50;
  public static final int BREAK = 18;
  public static final int VOID = 38;
  public static final int MULEQ = 44;
  public static final int MODULE = 41;
  public static final int ISNOTEQUAL = 30;
  public static final int LBRACE = 3;
  public static final int ELSE = 25;
  public static final int READ = 20;
  public static final int CHARCONST = 48;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 49;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int GREEQUAL = 32;
  public static final int PRINT = 22;
}

